import path from "node:path";
import { defineConfig } from "vitest/config";

export default defineConfig({
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  test: {
    // Every test file shares one Postgres database and truncates between
    // tests — running files in parallel would let them clobber each other.
    fileParallelism: false,
    globalSetup: ["./src/test/global-setup.ts"],
    env: {
      NODE_ENV: "test",
    },
    /*
     * Coverage is a map of what the suite never reaches, not a score.
     *
     * The tests that matter most here are behavioural — one school's query
     * returning none of another's rows, a payment matcher that leaves an
     * ambiguous reference unmatched rather than guessing — and none of those
     * move a percentage much. What this is good for is the opposite: a file
     * nobody tests at all, which the number does show.
     *
     * No thresholds, deliberately. A build that fails at 79.9% teaches people
     * to write tests that touch lines, and a green 80% invites trusting a
     * suite that never asserted anything about the half that matters.
     */
    coverage: {
      provider: "v8",
      reporter: ["text-summary", "html", "lcov"],
      reportsDirectory: "./coverage",
      include: ["src/**/*.ts"],
      exclude: [
        // Test scaffolding and the tests themselves.
        "src/**/*.test.ts",
        "src/test/**",
        // Generated by the Better Auth CLI, not written here.
        "src/db/auth-schema.ts",
        // Table definitions and migration entry points: declarations and a
        // driver call, so a percentage against them says nothing.
        "src/db/schema.ts",
        "src/db/migrate.ts",
        // Process entry points, exercised by the docker smoke test in CI
        // rather than by vitest.
        "src/index.ts",
        // Types only — it erases to nothing, so it reports 0% forever and
        // says nothing about the suite.
        "src/lib/types.ts",
      ],
    },
  },
});
